// Catalogue des cultures disponibles, classées par familles :
// légumes-feuilles, légumes-fruits et légumes-racines.
//
// Métriques (en mois, à partir de la plantation/repiquage en place) :
// - harvestFromMonths : début de récolte possible
// - totalMonths : temps de culture total (au-delà, la culture disparaît)
// - shelterHarvestFromMonths / shelterTotalMonths : déclinaisons sous abri
//   (récolte souvent plus précoce, saison parfois prolongée)
export const CATEGORIES = {
  feuille: 'Légumes-feuilles',
  fruit: 'Légumes-fruits',
  racine: 'Légumes-racines',
}

export const CROPS = {
  // --- Légumes-feuilles ---
  poireau: {
    id: 'poireau',
    name: 'Poireau',
    emoji: '🥬',
    color: '#4a7c3a',
    category: 'feuille',
    harvestFromMonths: 5,
    totalMonths: 10,
    shelterHarvestFromMonths: 4,
    shelterTotalMonths: 10,
    rowSpacingCm: 40,
    plantSpacingCm: 20,
  },
  laitue: {
    id: 'laitue',
    name: 'Laitue',
    emoji: '🥗',
    color: '#7dbb5c',
    category: 'feuille',
    harvestFromMonths: 2,
    totalMonths: 3,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 3,
    rowSpacingCm: 30,
    plantSpacingCm: 25,
  },
  epinard: {
    id: 'epinard',
    name: 'Épinard',
    emoji: '🍃',
    color: '#2f7d4f',
    category: 'feuille',
    harvestFromMonths: 2,
    totalMonths: 4,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 4,
    rowSpacingCm: 30,
    plantSpacingCm: 10,
  },
  chou: {
    id: 'chou',
    name: 'Chou pommé',
    emoji: '🥬',
    color: '#5a9c6e',
    category: 'feuille',
    harvestFromMonths: 3,
    totalMonths: 6,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 6,
    rowSpacingCm: 60,
    plantSpacingCm: 50,
  },
  blette: {
    id: 'blette',
    name: 'Blette',
    emoji: '🌿',
    color: '#3f8f5a',
    category: 'feuille',
    harvestFromMonths: 2,
    totalMonths: 8,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 9,
    rowSpacingCm: 40,
    plantSpacingCm: 30,
  },
  celeri: {
    id: 'celeri',
    name: 'Céleri branche',
    emoji: '🌿',
    color: '#82a860',
    category: 'feuille',
    harvestFromMonths: 5,
    totalMonths: 7,
    shelterHarvestFromMonths: 4,
    shelterTotalMonths: 7,
    rowSpacingCm: 40,
    plantSpacingCm: 30,
  },
  mache: {
    id: 'mache',
    name: 'Mâche',
    emoji: '🌱',
    color: '#5e8c4a',
    category: 'feuille',
    harvestFromMonths: 2,
    totalMonths: 5,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 6,
    rowSpacingCm: 20,
    plantSpacingCm: 8,
  },

  // --- Légumes-fruits ---
  tomate: {
    id: 'tomate',
    name: 'Tomate',
    emoji: '🍅',
    color: '#c0392b',
    category: 'fruit',
    harvestFromMonths: 2,
    totalMonths: 5,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 7,
    rowSpacingCm: 80,
    plantSpacingCm: 50,
  },
  courgette: {
    id: 'courgette',
    name: 'Courgette',
    emoji: '🥒',
    color: '#2e8b57',
    category: 'fruit',
    harvestFromMonths: 2,
    totalMonths: 5,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 6,
    rowSpacingCm: 100,
    plantSpacingCm: 80,
  },
  concombre: {
    id: 'concombre',
    name: 'Concombre',
    emoji: '🥒',
    color: '#3a9d6e',
    category: 'fruit',
    harvestFromMonths: 2,
    totalMonths: 4,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 5,
    rowSpacingCm: 100,
    plantSpacingCm: 40,
  },
  poivron: {
    id: 'poivron',
    name: 'Poivron',
    emoji: '🫑',
    color: '#d35400',
    category: 'fruit',
    harvestFromMonths: 3,
    totalMonths: 6,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 7,
    rowSpacingCm: 60,
    plantSpacingCm: 50,
  },
  aubergine: {
    id: 'aubergine',
    name: 'Aubergine',
    emoji: '🍆',
    color: '#6c3483',
    category: 'fruit',
    harvestFromMonths: 3,
    totalMonths: 6,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 7,
    rowSpacingCm: 60,
    plantSpacingCm: 50,
  },
  courges: {
    id: 'courges',
    name: 'Courges',
    emoji: '🎃',
    color: '#ca6f1e',
    category: 'fruit',
    harvestFromMonths: 4,
    totalMonths: 5,
    shelterHarvestFromMonths: 3,
    shelterTotalMonths: 5,
    rowSpacingCm: 200,
    plantSpacingCm: 150,
  },
  haricotVert: {
    id: 'haricotVert',
    name: 'Haricot vert',
    emoji: '🫘',
    color: '#4f9d4f',
    category: 'fruit',
    harvestFromMonths: 2,
    totalMonths: 4,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 4,
    rowSpacingCm: 40,
    plantSpacingCm: 10,
  },
  petitPois: {
    id: 'petitPois',
    name: 'Petit pois',
    emoji: '🫛',
    color: '#66a05b',
    category: 'fruit',
    harvestFromMonths: 3,
    totalMonths: 4,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 4,
    rowSpacingCm: 40,
    plantSpacingCm: 5,
  },
  melon: {
    id: 'melon',
    name: 'Melon',
    emoji: '🍈',
    color: '#b7950b',
    category: 'fruit',
    harvestFromMonths: 3,
    totalMonths: 5,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 5,
    rowSpacingCm: 100,
    plantSpacingCm: 80,
  },
  mais: {
    id: 'mais',
    name: 'Maïs doux',
    emoji: '🌽',
    color: '#d4ac0d',
    category: 'fruit',
    harvestFromMonths: 3,
    totalMonths: 4,
    shelterHarvestFromMonths: 3,
    shelterTotalMonths: 4,
    rowSpacingCm: 70,
    plantSpacingCm: 20,
  },

  // --- Légumes-racines ---
  carotte: {
    id: 'carotte',
    name: 'Carotte',
    emoji: '🥕',
    color: '#e67e22',
    category: 'racine',
    harvestFromMonths: 3,
    totalMonths: 6,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 5,
    rowSpacingCm: 25,
    plantSpacingCm: 5,
  },
  pommeDeTerre: {
    id: 'pommeDeTerre',
    name: 'Pomme de terre',
    emoji: '🥔',
    color: '#a58a5c',
    category: 'racine',
    harvestFromMonths: 3,
    totalMonths: 5,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 4,
    rowSpacingCm: 70,
    plantSpacingCm: 35,
  },
  radis: {
    id: 'radis',
    name: 'Radis',
    emoji: '🔴',
    color: '#c74d5e',
    category: 'racine',
    harvestFromMonths: 1,
    totalMonths: 2,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 2,
    rowSpacingCm: 20,
    plantSpacingCm: 3,
  },
  betterave: {
    id: 'betterave',
    name: 'Betterave',
    emoji: '🟣',
    color: '#8e3a59',
    category: 'racine',
    harvestFromMonths: 3,
    totalMonths: 6,
    shelterHarvestFromMonths: 2,
    shelterTotalMonths: 5,
    rowSpacingCm: 30,
    plantSpacingCm: 10,
  },
  navet: {
    id: 'navet',
    name: 'Navet',
    emoji: '⚪',
    color: '#b8a9c9',
    category: 'racine',
    harvestFromMonths: 2,
    totalMonths: 4,
    shelterHarvestFromMonths: 1,
    shelterTotalMonths: 3,
    rowSpacingCm: 30,
    plantSpacingCm: 10,
  },
  panais: {
    id: 'panais',
    name: 'Panais',
    emoji: '🟡',
    color: '#c9b26b',
    category: 'racine',
    harvestFromMonths: 4,
    totalMonths: 8,
    shelterHarvestFromMonths: 3,
    shelterTotalMonths: 7,
    rowSpacingCm: 40,
    plantSpacingCm: 10,
  },
  oignon: {
    id: 'oignon',
    name: 'Oignon',
    emoji: '🧅',
    color: '#b9770e',
    category: 'racine',
    harvestFromMonths: 4,
    totalMonths: 6,
    shelterHarvestFromMonths: 3,
    shelterTotalMonths: 5,
    rowSpacingCm: 30,
    plantSpacingCm: 10,
  },
  echalote: {
    id: 'echalote',
    name: 'Échalote',
    emoji: '🧅',
    color: '#a9746e',
    category: 'racine',
    harvestFromMonths: 4,
    totalMonths: 6,
    shelterHarvestFromMonths: 3,
    shelterTotalMonths: 5,
    rowSpacingCm: 30,
    plantSpacingCm: 15,
  },
  ail: {
    id: 'ail',
    name: 'Ail',
    emoji: '🧄',
    color: '#c8c2ae',
    category: 'racine',
    harvestFromMonths: 6,
    totalMonths: 8,
    shelterHarvestFromMonths: 5,
    shelterTotalMonths: 7,
    rowSpacingCm: 30,
    plantSpacingCm: 10,
  },
}

// Fenêtres d'implantation en pleine terre (out) et sous abri (shelter).
// Plages de mois [début, fin] inclus (1 = janvier ... 12 = décembre).
// Sources : calendriers de plantation usuels pour climat tempéré (France).
const PLANT_WINDOWS = {
  // Feuilles
  poireau: { out: [[5, 7]], shelter: [[3, 4]] },
  laitue: { out: [[4, 9]], shelter: [[2, 3], [9, 10]] },
  epinard: { out: [[3, 5], [8, 9]], shelter: [[2, 2], [10, 10]] },
  chou: { out: [[4, 7]], shelter: [[2, 3]] },
  blette: { out: [[4, 7]], shelter: [[3, 3]] },
  celeri: { out: [[5, 6]], shelter: [[4, 4]] },
  mache: { out: [[8, 10]], shelter: [[8, 11]] },
  // Fruits
  tomate: { out: [[5, 6]], shelter: [[3, 4]] },
  courgette: { out: [[5, 6]], shelter: [[4, 4]] },
  concombre: { out: [[5, 6]], shelter: [[4, 4]] },
  poivron: { out: [[5, 6]], shelter: [[4, 4]] },
  aubergine: { out: [[5, 6]], shelter: [[4, 4]] },
  courges: { out: [[5, 6]], shelter: [[4, 4]] },
  haricotVert: { out: [[5, 7]], shelter: [[4, 4]] },
  petitPois: { out: [[2, 4], [10, 11]], shelter: [[1, 2]] },
  melon: { out: [[5, 6]], shelter: [[4, 4]] },
  mais: { out: [[5, 6]], shelter: [[4, 4]] },
  // Racines
  carotte: { out: [[3, 7]], shelter: [[2, 2]] },
  pommeDeTerre: { out: [[3, 5]], shelter: [[2, 2]] },
  radis: { out: [[3, 9]], shelter: [[2, 2], [10, 10]] },
  betterave: { out: [[4, 6]], shelter: [[3, 3]] },
  navet: { out: [[3, 6], [8, 9]], shelter: [[2, 2]] },
  panais: { out: [[2, 6]], shelter: [] },
  oignon: { out: [[2, 4], [9, 10]], shelter: [] },
  echalote: { out: [[2, 3], [10, 11]], shelter: [] },
  ail: { out: [[1, 2], [10, 12]], shelter: [] },
}

for (const [id, w] of Object.entries(PLANT_WINDOWS)) {
  if (CROPS[id]) {
    CROPS[id].plantWindows = w.out
    CROPS[id].shelterPlantWindows = w.shelter
  }
}

// Semis en godet (pépinière au chaud) pour les légumes qui se plantent
// en petits plants : nombre de jours entre le semis et l'implantation.
// 0 / absent = semis direct en place. Paramétrable dans l'écran Paramétrage.
// Sources : durées d'élevage de plants usuelles.
const NURSERY_DAYS = {
  tomate: 56,
  poivron: 70,
  aubergine: 70,
  courgette: 28,
  concombre: 28,
  melon: 28,
  courges: 28,
  chou: 42,
  laitue: 28,
  celeri: 70,
  poireau: 70,
  blette: 28,
  mais: 21,
}

for (const [id, days] of Object.entries(NURSERY_DAYS)) {
  if (CROPS[id]) CROPS[id].nurseryDays = days
}

// Un mois (1-12) est-il dans l'une des plages ?
export function monthInWindows(month, windows = []) {
  return windows.some(([from, to]) => month >= from && month <= to)
}

export function getCrop(id) {
  return CROPS[id]
}
